# ../docker-compose.yml
version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: .
    image: image-app-frontend
    ports:
     - "3000:3000"
    environment:
     - VITE_BACKEND_URL=https://orgiy71zxj.execute-api.us-east-1.amazonaws.com/
    working_dir: /app
    volumes: 
    - ./src:/app/src
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

